---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cpe0000784/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp bulkhours.html $DEPLOYPATH
    - /bin/cp containt_en.xml $DEPLOYPATH
    - /bin/cp containt_fr.xml $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    